### ISSUE TITLE
FEATURE REQUEST: allow content on section page

### ISSUE THREAD

**Issue by tbrowder** [codeandmedia/zola_docsascode_theme#3]
It would be nice if we could have the ability to have some fixed content below the title on the left column of a section page.

**Comment by codeandmedia** [comment]
do you mean something like that? 

![изображение](https://user-images.githubusercontent.com/59285587/95584236-0868b380-0a46-11eb-93c8-bb58fedce45e.png)

**Comment by tbrowder** [comment]
Yes! Did I miss something in the docs, or is that a macro or template change?

Or is it from the section "description" text? I tried that and couldn't see a change, but it was early in my testing and I may have missed it.

**Comment by codeandmedia** [comment]
You can add `<div style="margin-bottom:1rem;">Your text here </div>` below the title in section.html (https://github.com/codeandmedia/zola_docsascode_theme/blob/9111586be055a3ac7bc56e28b197eb8cf6662046/templates/section.html#L13)

**Comment by tbrowder** [comment]
Thank you!
