### ISSUE TITLE
Installation instruction conflict with those found on Zola's section on themes

### ISSUE THREAD

**Issue by alice-i-cecile** [codeandmedia/zola_docsascode_theme#4]
The [official instructions](https://www.getzola.org/documentation/themes/installing-and-using-themes/) suggest to clone this repo into the themes folder. This conflicts with the advice in this repo's README.md advising us to begin by forking the project.

**Comment by codeandmedia** [comment]
Both ways are workable. When you start your zola's project locally from the scratch you could clone the repo to themes folder, edit config.toml, add content and use the website. Or, you can fork the repo, delete my demo content and add yours. It would be useful if you want to build docker image or don't want to have something locally.

**Comment by kaihendry** [comment]
Why don't you advertise the clone URL https://github.com/codeandmedia/zola_docsascode_theme.git upon https://docsascode.codeandmedia.com ?

**Comment by codeandmedia** [comment]
> 
> 
> Why don't you advertise the clone URL https://github.com/codeandmedia/zola_docsascode_theme.git upon https://docsascode.codeandmedia.com ?

Yes, you're right. I added the link to the index page
